# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-09 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_list_item_unique_together'),
        ('lists', '0005_auto_20190804_1015'),
    ]

    operations = [
    ]
